---
- hosts: localhost
  connection: local
  become: true
  vars:
    - elastic_ver: '6.3'

  tasks:
    - name: Installation apt-transport-https
      apt:
        name: "apt-transport-https"
        state: "present"

    - name: Installation ca-certificates
      apt:
        name: "ca-certificates"
        state: "latest"

    - name: Installation JRE
      apt:
        name: "openjdk-8-jdk"
        state: "present"

    - name: Ajout de la clé du Repo Elasticsearch
      apt_key:
        url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        state: "present"

    - name: Ajout du Repo Elasticsearch
      #apt_repository:
      # repo: "deb https://packages.elastic.co/elasticsearch/{{ elastic_ver }}/debian stable main"
      command: "echo 'deb https://artifacts.elastic.co/packages/{{ elastic_ver }}/apt stable main' | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list"

    - name: Installation Elasticsearch
      apt:
        name: "elasticsearch"
        state: "present"
        install_recommends: no
        update_cache: yes

    #- name: Vérification lancement ElasticSearch demarrage de Ubuntu
    #  command: "sudo systemctl enable elasticsearch.service"
    #  systemd:
    #    name: elasticsearch.service
    #    enabled: yes
    #    state: started
