version: '2'

services:
  elasticsearch:
    image: dockerelk_elastic
    build:
      context: elasticsearch/
    volumes:
      - "./.data:/usr/share/elasticsearch/data"
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - ./elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms256m"
    networks:
      - elk

  logstash:
    image: dockerelk_logstash
    build:
      context: logstash/
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config/:/usr/share/logstash/config/:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "10514:10514"
      - "10514:10514/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms256m"
    networks:
      - elk

  kibana:
    image: dockerelk_kibana
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk

networks:

  elk:
    driver: bridge
